# Generated by Django 5.2.1 on 2025-07-29 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prepdungeon', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUsEmail',
        ),
        migrations.DeleteModel(
            name='DailyEvent',
        ),
        migrations.DeleteModel(
            name='Waitlist',
        ),
    ]
