# Generated by Django 4.2.16 on 2025-07-17 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prepdungeon', '0008_waitlist_userphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('general', 'General Inquiry'), ('support', 'Support Request'), ('feedback', 'Feedback'), ('partnership', 'Partnership Opportunity'), ('bug', 'Bug Report'), ('feature', 'Feature Request')], max_length=32)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=16),
        ),
        migrations.AlterField(
            model_name='question',
            name='q_type',
            field=models.CharField(choices=[('mcq', 'MCQ'), ('conceptual', 'Conceptual'), ('speed', 'Speed')], max_length=16),
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_photo', to=settings.AUTH_USER_MODEL),
        ),
    ]
