# Generated by Django 5.2.1 on 2025-07-29 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=256)),
                ('topic', models.CharField(default='Misc', max_length=128)),
                ('subject', models.CharField(default='Misc', max_length=128)),
                ('q_type', models.CharField(choices=[('mcq', 'MCQ'), ('conceptual', 'Conceptual'), ('speed', 'Speed')], max_length=16)),
                ('option1', models.CharField(max_length=256, null=True)),
                ('option2', models.CharField(max_length=256, null=True)),
                ('option3', models.CharField(max_length=256, null=True)),
                ('option4', models.CharField(max_length=256, null=True)),
                ('answer', models.CharField(max_length=512, null=True)),
                ('level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='CompletedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('mcq', 'MCQ'), ('conceptual', 'Conceptual'), ('speed', 'Speed')], default='MCQ', max_length=16)),
                ('score', models.IntegerField(default=0)),
                ('analysis', models.TextField(default='No analysis available')),
                ('time_spent', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_tests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('time_spent', models.IntegerField(default=0)),
                ('completed_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='tests.completedtest')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.question')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
