# Generated by Django 5.2.1 on 2025-07-29 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('xp_reward', models.IntegerField(default=25)),
                ('points_reward', models.IntegerField(default=5)),
                ('quest_type', models.CharField(choices=[('read_material', 'Read Study Material'), ('complete_test', 'Complete a Test'), ('upload_document', 'Upload a Document'), ('score_90', 'Score 90% or higher'), ('score_80', 'Score 80% or higher'), ('complete_3_tests', 'Complete 3 Tests')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserDailyQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('daily_quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.dailyquest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_quests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Daily Quest',
                'verbose_name_plural': 'User Daily Quests',
                'unique_together': {('user', 'daily_quest', 'date_created')},
            },
        ),
    ]
